name: units_converter
description: Simple and light units conversion package for all your needs.
version: 2.0.0
homepage: https://github.com/ferraridamiano/units_converter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  decimal: ^2.2.0
  rational: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
